#############################################################################
# Makefile for building: test.app/Contents/MacOS/test
# Generated by qmake (3.1) (Qt 6.2.1)
# Project:  test.pro
# Template: app
# Command: /usr/local/bin/qmake -o test.xcodeproj/project.pbxproj test.pro -spec macx-xcode
#############################################################################

MAKEFILE      = project.pbxproj

EQ            = =

MOC       = /usr/local/share/qt/libexec/moc
UIC       = /usr/local/share/qt/libexec/uic
LEX       = flex
LEXFLAGS  = 
YACC      = yacc
YACCFLAGS = -d
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
INCPATH       = -I. -I/usr/local/lib/QtWidgets.framework/Headers -I/usr/local/lib/QtGui.framework/Headers -I/usr/local/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/System/Library/Frameworks/AGL.framework/Headers -I/usr/local/Cellar/qt/6.2.1/share/qt/mkspecs/macx-clang -F/usr/local/lib
DEL_FILE  = rm -f
MOVE      = mv -f

preprocess: compilers
clean preprocess_clean: compiler_clean

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compilers: moc_predefs.h moc_game.cpp moc_menu.cpp moc_button.cpp\
	 moc_MyPushButton.cpp moc_Warea.cpp moc_fight.cpp\
	 moc_fight_button.cpp ui_menu.h
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/local/share/qt/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++2a -Wall -Wextra -dM -E -o moc_predefs.h /usr/local/share/qt/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_game.cpp moc_menu.cpp moc_button.cpp moc_MyPushButton.cpp moc_Warea.cpp moc_fight.cpp moc_fight_button.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_game.cpp moc_menu.cpp moc_button.cpp moc_MyPushButton.cpp moc_Warea.cpp moc_fight.cpp moc_fight_button.cpp
moc_game.cpp: ../../labs/summoning_game/summoning_game/game.hpp \
		../../labs/summoning_game/summoning_game/menu.hpp \
		../../labs/summoning_game/summoning_game/Summoner.hpp \
		/usr/local/lib/QtGui.framework/Headers/QtGui \
		../../labs/summoning_game/summoning_game/Schools.hpp \
		/usr/local/lib/QtGui.framework/Headers/QPixmap \
		/usr/local/lib/QtWidgets.framework/Headers/QApplication \
		../../labs/summoning_game/summoning_game/graph.hpp \
		/usr/local/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/usr/local/lib/QtGui.framework/Headers/QAction \
		/usr/local/lib/QtWidgets.framework/Headers/QMenuBar \
		/usr/local/lib/QtWidgets.framework/Headers/QMenu \
		/usr/local/lib/QtWidgets.framework/Headers/QDialog \
		/usr/local/lib/QtWidgets.framework/Headers/QMainWindow \
		/usr/local/lib/QtWidgets.framework/Headers/QLineEdit \
		/usr/local/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/lib/QtWidgets.framework/Headers/QGridLayout \
		/usr/local/lib/QtWidgets.framework/Headers/QHBoxLayout \
		/usr/local/lib/QtWidgets.framework/Headers/QMessageBox \
		../../labs/summoning_game/summoning_game/landscape.hpp \
		Warea.hpp \
		MyPushButton.hpp \
		/usr/local/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/lib/QtCore.framework/Headers/QObject \
		moc_predefs.h \
		/usr/local/share/qt/libexec/moc
	/usr/local/share/qt/libexec/moc $(DEFINES) --include /Users/pavelshykov/Desktop/Qtest/test/moc_predefs.h -I/usr/local/Cellar/qt/6.2.1/share/qt/mkspecs/macx-clang -I/Users/pavelshykov/Desktop/Qtest/test -I/usr/local/lib/QtWidgets.framework/Headers -I/usr/local/lib/QtGui.framework/Headers -I/usr/local/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/usr/local/lib ../../labs/summoning_game/summoning_game/game.hpp -o moc_game.cpp

moc_menu.cpp: ../../labs/summoning_game/summoning_game/menu.hpp \
		../../labs/summoning_game/summoning_game/Summoner.hpp \
		/usr/local/lib/QtGui.framework/Headers/QtGui \
		../../labs/summoning_game/summoning_game/Schools.hpp \
		/usr/local/lib/QtGui.framework/Headers/QPixmap \
		/usr/local/lib/QtWidgets.framework/Headers/QApplication \
		../../labs/summoning_game/summoning_game/graph.hpp \
		/usr/local/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/usr/local/lib/QtGui.framework/Headers/QAction \
		/usr/local/lib/QtWidgets.framework/Headers/QMenuBar \
		/usr/local/lib/QtWidgets.framework/Headers/QMenu \
		/usr/local/lib/QtWidgets.framework/Headers/QDialog \
		/usr/local/lib/QtWidgets.framework/Headers/QMainWindow \
		/usr/local/lib/QtWidgets.framework/Headers/QLineEdit \
		/usr/local/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/lib/QtWidgets.framework/Headers/QGridLayout \
		/usr/local/lib/QtWidgets.framework/Headers/QHBoxLayout \
		/usr/local/lib/QtWidgets.framework/Headers/QMessageBox \
		moc_predefs.h \
		/usr/local/share/qt/libexec/moc
	/usr/local/share/qt/libexec/moc $(DEFINES) --include /Users/pavelshykov/Desktop/Qtest/test/moc_predefs.h -I/usr/local/Cellar/qt/6.2.1/share/qt/mkspecs/macx-clang -I/Users/pavelshykov/Desktop/Qtest/test -I/usr/local/lib/QtWidgets.framework/Headers -I/usr/local/lib/QtGui.framework/Headers -I/usr/local/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/usr/local/lib ../../labs/summoning_game/summoning_game/menu.hpp -o moc_menu.cpp

moc_button.cpp: button.hpp \
		/usr/local/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/lib/QtGui.framework/Headers/QPainter \
		/usr/local/lib/QtCore.framework/Headers/QDebug \
		/usr/local/lib/QtGui.framework/Headers/QPaintEvent \
		/usr/local/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/lib/QtCore.framework/Headers/QEvent \
		/usr/local/lib/QtGui.framework/Headers/QMouseEvent \
		/usr/local/lib/QtWidgets.framework/Headers/QMenu \
		/usr/local/lib/QtWidgets.framework/Headers/QColorDialog \
		/usr/local/lib/QtWidgets.framework/Headers/QScrollBar \
		moc_predefs.h \
		/usr/local/share/qt/libexec/moc
	/usr/local/share/qt/libexec/moc $(DEFINES) --include /Users/pavelshykov/Desktop/Qtest/test/moc_predefs.h -I/usr/local/Cellar/qt/6.2.1/share/qt/mkspecs/macx-clang -I/Users/pavelshykov/Desktop/Qtest/test -I/usr/local/lib/QtWidgets.framework/Headers -I/usr/local/lib/QtGui.framework/Headers -I/usr/local/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/usr/local/lib button.hpp -o moc_button.cpp

moc_MyPushButton.cpp: MyPushButton.hpp \
		/usr/local/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/lib/QtGui.framework/Headers/QPixmap \
		/usr/local/lib/QtWidgets.framework/Headers/QApplication \
		/usr/local/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/lib/QtCore.framework/Headers/QObject \
		moc_predefs.h \
		/usr/local/share/qt/libexec/moc
	/usr/local/share/qt/libexec/moc $(DEFINES) --include /Users/pavelshykov/Desktop/Qtest/test/moc_predefs.h -I/usr/local/Cellar/qt/6.2.1/share/qt/mkspecs/macx-clang -I/Users/pavelshykov/Desktop/Qtest/test -I/usr/local/lib/QtWidgets.framework/Headers -I/usr/local/lib/QtGui.framework/Headers -I/usr/local/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/usr/local/lib MyPushButton.hpp -o moc_MyPushButton.cpp

moc_Warea.cpp: Warea.hpp \
		MyPushButton.hpp \
		/usr/local/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/lib/QtGui.framework/Headers/QPixmap \
		/usr/local/lib/QtWidgets.framework/Headers/QApplication \
		/usr/local/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/lib/QtCore.framework/Headers/QObject \
		moc_predefs.h \
		/usr/local/share/qt/libexec/moc
	/usr/local/share/qt/libexec/moc $(DEFINES) --include /Users/pavelshykov/Desktop/Qtest/test/moc_predefs.h -I/usr/local/Cellar/qt/6.2.1/share/qt/mkspecs/macx-clang -I/Users/pavelshykov/Desktop/Qtest/test -I/usr/local/lib/QtWidgets.framework/Headers -I/usr/local/lib/QtGui.framework/Headers -I/usr/local/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/usr/local/lib Warea.hpp -o moc_Warea.cpp

moc_fight.cpp: fight.hpp \
		MyPushButton.hpp \
		/usr/local/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/lib/QtGui.framework/Headers/QPixmap \
		/usr/local/lib/QtWidgets.framework/Headers/QApplication \
		/usr/local/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/lib/QtCore.framework/Headers/QObject \
		moc_predefs.h \
		/usr/local/share/qt/libexec/moc
	/usr/local/share/qt/libexec/moc $(DEFINES) --include /Users/pavelshykov/Desktop/Qtest/test/moc_predefs.h -I/usr/local/Cellar/qt/6.2.1/share/qt/mkspecs/macx-clang -I/Users/pavelshykov/Desktop/Qtest/test -I/usr/local/lib/QtWidgets.framework/Headers -I/usr/local/lib/QtGui.framework/Headers -I/usr/local/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/usr/local/lib fight.hpp -o moc_fight.cpp

moc_fight_button.cpp: fight_button.hpp \
		/usr/local/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/lib/QtGui.framework/Headers/QPixmap \
		/usr/local/lib/QtWidgets.framework/Headers/QApplication \
		/usr/local/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/lib/QtCore.framework/Headers/QObject \
		moc_predefs.h \
		/usr/local/share/qt/libexec/moc
	/usr/local/share/qt/libexec/moc $(DEFINES) --include /Users/pavelshykov/Desktop/Qtest/test/moc_predefs.h -I/usr/local/Cellar/qt/6.2.1/share/qt/mkspecs/macx-clang -I/Users/pavelshykov/Desktop/Qtest/test -I/usr/local/lib/QtWidgets.framework/Headers -I/usr/local/lib/QtGui.framework/Headers -I/usr/local/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/usr/local/lib fight_button.hpp -o moc_fight_button.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_menu.h
compiler_uic_clean:
	-$(DEL_FILE) ui_menu.h
ui_menu.h: menu.ui \
		/usr/local/share/qt/libexec/uic
	/usr/local/share/qt/libexec/uic menu.ui -o ui_menu.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

